server {
    listen 80;
    server_name vps.recordweb.dev;

    location /fragenmanagement/ {
        alias /usr/share/nginx/html/apps/fragenmanagement/;
        index fragenmanagement.html;
    }

    location /antwortmanagement/ {
        alias /usr/share/nginx/html/apps/antwortmanagement/;
        index antwortmanagement.html;
    }

    location = /fragestunde {
        return 301 /fragestunde/;
    }

    location /fragestunde/ {
        alias /usr/share/nginx/html/apps/fragestunde-web/frontend/;
        index fragenmanagement.html;
    }

    location /api/ {
        proxy_pass http://api:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        return 200 'PoC-Server laeuft. Verfuegbare Apps: /fragenmanagement/ /antwortmanagement/ /fragestunde/';
        add_header Content-Type text/plain;
    }
}
