server {
    listen 80;
    server_name vps.recordweb.dev;

    location /fragenmanagement/ {
        alias /usr/share/nginx/html/apps/fragenmanagement/;
        index fragenmanagement.html;
    }

    location /antwortmanagement/ {
        alias /usr/share/nginx/html/apps/antwortmanagement/;
        index antwortmanagement.html;
    }

    location / {
        return 200 'PoC-Server laeuft. Verfuegbare Apps: /fragenmanagement/ /antwortmanagement/';
        add_header Content-Type text/plain;
    }
}
