server {
    listen 80;
    server_name vps.recordweb.dev;

    location = /fragenmanagement {
        return 301 /fragenmanagement/;
    }

    location /fragenmanagement/ {
        alias /usr/share/nginx/html/apps/fragenmanagement/frontend/;
        index fragenmanagement.html;
    }

    location /fragenmanagement/api/ {
        proxy_pass http://api:3000/fragenmanagement/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /fragenmanagement/did/ {
        proxy_pass http://api:3000/fragenmanagement/did/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /fragenmanagement/api-docs/ {
        proxy_pass http://api:3000/fragenmanagement/api-docs/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /resolver/parlament/frontend/ {
        alias /usr/share/nginx/html/apps/resolver/frontend/;
        index admin.html;
    }

    location /resolver/parlament/ {
        proxy_pass http://resolver-parlament:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /resolver/bk/frontend/ {
        alias /usr/share/nginx/html/apps/resolver/frontend/;
        index admin.html;
    }

    location /resolver/bk/ {
        proxy_pass http://resolver-bk:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    location / {
        return 200 'PoC-Server laeuft. Verfuegbare Apps: /fragenmanagement/ /antwortmanagement/';
        add_header Content-Type text/plain;
    }
}
